namespace Atlas.Features.Shared;

public static class FilterList
{
    public static List<string> CountryFilters =
    [
        "overview",
        "general information",
        "basic facts",
        "history",
        "ancient history",
        "medieval history",
        "modern history",
        "colonial history",
        "independence history",
        "recent history",
        "historical timeline",
        "major historical events",
        "historical leaders",
        "wars",
        "civil wars",
        "revolutions",
        "independence date",
        "founding date",
        "former names",
        "former territories",
        "historical empires",
        "archaeological sites",
        "unesco world heritage sites",
        "geography",
        "location",
        "coordinates",
        "continent",
        "region",
        "subregion",
        "area",
        "land area",
        "water area",
        "coastline length",
        "borders",
        "border length",
        "neighboring countries",
        "maritime borders",
        "capital",
        "largest city",
        "largest cities",
        "major cities",
        "urban areas",
        "rural areas",
        "administrative divisions",
        "states",
        "provinces",
        "regions",
        "districts",
        "municipalities",
        "time zones",
        "daylight saving time",
        "climate",
        "climate zones",
        "average temperature",
        "average rainfall",
        "seasons",
        "weather patterns",
        "natural disasters",
        "earthquakes",
        "floods",
        "droughts",
        "hurricanes",
        "volcanoes",
        "mountains",
        "highest point",
        "lowest point",
        "rivers",
        "longest river",
        "lakes",
        "largest lake",
        "deserts",
        "forests",
        "islands",
        "peninsulas",
        "valleys",
        "plains",
        "natural resources",
        "mineral resources",
        "oil reserves",
        "gas reserves",
        "coal reserves",
        "freshwater resources",
        "land use",
        "agricultural land",
        "forest area",
        "protected areas",
        "national parks",
        "biodiversity",
        "endangered species",
        "native species",
        "invasive species",
        "environment",
        "environmental issues",
        "pollution",
        "air pollution",
        "water pollution",
        "soil pollution",
        "carbon emissions",
        "greenhouse gas emissions",
        "deforestation",
        "desertification",
        "waste management",
        "recycling rate",
        "renewable energy",
        "energy mix",
        "electricity production",
        "electricity access",
        "energy consumption",
        "population",
        "population growth",
        "population density",
        "population ranking",
        "age distribution",
        "median age",
        "children population",
        "youth population",
        "working age population",
        "elderly population",
        "dependency ratio",
        "birth rate",
        "death rate",
        "fertility rate",
        "infant mortality rate",
        "maternal mortality rate",
        "life expectancy",
        "male life expectancy",
        "female life expectancy",
        "gender ratio",
        "women vs men population",
        "male population",
        "female population",
        "urban population",
        "rural population",
        "urbanization rate",
        "household size",
        "families",
        "marriage rate",
        "divorce rate",
        "migration rate",
        "net migration rate",
        "immigration",
        "emigration",
        "refugees",
        "asylum seekers",
        "diaspora",
        "ethnic groups",
        "tribes",
        "indigenous peoples",
        "languages",
        "official languages",
        "spoken languages",
        "minority languages",
        "language families",
        "literacy rate",
        "male literacy rate",
        "female literacy rate",
        "religion",
        "religions",
        "major religion",
        "religious demographics",
        "religious freedom",
        "culture",
        "traditions",
        "customs",
        "social norms",
        "etiquette",
        "national identity",
        "national symbols",
        "flag",
        "flag meaning",
        "coat of arms",
        "national anthem",
        "national motto",
        "national animal",
        "national bird",
        "national flower",
        "national tree",
        "national sport",
        "national holidays",
        "public holidays",
        "festivals",
        "traditional clothing",
        "traditional music",
        "traditional dance",
        "traditional art",
        "handicrafts",
        "folklore",
        "mythology",
        "cuisine",
        "food",
        "traditional dishes",
        "street food",
        "drinks",
        "tea culture",
        "coffee culture",
        "dining customs",
        "arts",
        "literature",
        "poetry",
        "cinema",
        "theater",
        "architecture",
        "museums",
        "music",
        "dance",
        "sports",
        "popular sports",
        "olympic participation",
        "olympic medals",
        "football",
        "basketball",
        "cricket",
        "rugby",
        "athletics",
        "government",
        "government type",
        "political system",
        "constitution",
        "constitution date",
        "head of state",
        "head of government",
        "president",
        "prime minister",
        "monarch",
        "parliament",
        "legislature",
        "political parties",
        "elections",
        "election system",
        "voting age",
        "administrative capital",
        "legal system",
        "judiciary",
        "supreme court",
        "law enforcement",
        "human rights",
        "civil rights",
        "freedom index",
        "press freedom",
        "internet freedom",
        "religious freedom",
        "corruption index",
        "democracy index",
        "rule of law",
        "international relations",
        "foreign policy",
        "diplomatic relations",
        "embassies",
        "international organizations",
        "un membership",
        "regional organizations",
        "military",
        "armed forces",
        "army",
        "navy",
        "air force",
        "military service",
        "conscription",
        "defense spending",
        "military personnel",
        "peacekeeping missions",
        "security",
        "internal security",
        "border security",
        "terrorism risk",
        "crime rate",
        "violent crime",
        "homicide rate",
        "theft rate",
        "cybercrime",
        "prison population",
        "economy",
        "economic overview",
        "gdp",
        "nominal gdp",
        "gdp ppp",
        "gdp per capita",
        "gdp growth rate",
        "economic growth",
        "economic sectors",
        "agriculture sector",
        "industry sector",
        "services sector",
        "main industries",
        "industrial production",
        "manufacturing",
        "agriculture",
        "fishing",
        "forestry",
        "mining",
        "oil production",
        "gas production",
        "tourism sector",
        "technology sector",
        "financial sector",
        "banking sector",
        "stock market",
        "currency",
        "exchange rate",
        "central bank",
        "inflation rate",
        "interest rate",
        "unemployment rate",
        "youth unemployment rate",
        "employment rate",
        "labor force",
        "minimum wage",
        "average salary",
        "median income",
        "household income",
        "income inequality",
        "gini index",
        "poverty rate",
        "extreme poverty rate",
        "cost of living",
        "consumer price index",
        "public debt",
        "external debt",
        "government budget",
        "budget deficit",
        "tax revenue",
        "tax system",
        "corporate tax",
        "income tax",
        "vat",
        "sales tax",
        "exports",
        "imports",
        "trade balance",
        "main exports",
        "main imports",
        "trade partners",
        "export partners",
        "import partners",
        "foreign direct investment",
        "remittances",
        "economic freedom",
        "ease of doing business",
        "business environment",
        "startups",
        "innovation",
        "research and development",
        "patents",
        "education",
        "education system",
        "primary education",
        "secondary education",
        "higher education",
        "vocational education",
        "school enrollment",
        "primary school enrollment",
        "secondary school enrollment",
        "university enrollment",
        "graduated people",
        "number of graduated people",
        "university graduates",
        "higher education rate",
        "graduation rate",
        "male graduates",
        "female graduates",
        "stem graduates",
        "literacy rate",
        "education spending",
        "public education spending",
        "private education",
        "public schools",
        "universities",
        "top universities",
        "student population",
        "teacher population",
        "student teacher ratio",
        "school life expectancy",
        "adult education",
        "research institutions",
        "healthcare",
        "healthcare system",
        "public healthcare",
        "private healthcare",
        "healthcare spending",
        "healthcare spending per capita",
        "hospitals",
        "hospital beds",
        "doctors",
        "doctors per capita",
        "nurses",
        "nurses per capita",
        "dentists",
        "pharmacies",
        "health insurance",
        "universal healthcare",
        "vaccination rate",
        "disease burden",
        "common diseases",
        "communicable diseases",
        "noncommunicable diseases",
        "obesity rate",
        "smoking rate",
        "alcohol consumption",
        "mental health",
        "suicide rate",
        "maternal health",
        "child health",
        "nutrition",
        "undernourishment",
        "access to clean water",
        "access to sanitation",
        "infrastructure",
        "transport infrastructure",
        "road network",
        "road length",
        "highways",
        "railways",
        "railway length",
        "metro systems",
        "public transport",
        "bus network",
        "airports",
        "major airports",
        "national airline",
        "ports",
        "seaports",
        "inland waterways",
        "logistics",
        "internet access",
        "internet users",
        "broadband access",
        "mobile network coverage",
        "mobile subscriptions",
        "5g coverage",
        "telephone system",
        "postal system",
        "housing",
        "housing market",
        "home ownership",
        "rent prices",
        "utilities",
        "water supply",
        "sanitation",
        "electricity grid",
        "science",
        "technology",
        "digital economy",
        "e government",
        "cybersecurity",
        "space program",
        "artificial intelligence",
        "biotechnology",
        "media",
        "television",
        "radio",
        "newspapers",
        "social media usage",
        "internet domain",
        "country code",
        "calling code",
        "vehicle code",
        "iso codes",
        "iso alpha 2 code",
        "iso alpha 3 code",
        "numeric country code",
        "top level domain",
        "tourism",
        "tourist attractions",
        "tourism revenue",
        "annual visitors",
        "most visited places",
        "landmarks",
        "beaches",
        "historic sites",
        "religious sites",
        "natural attractions",
        "visa requirements",
        "passport ranking",
        "travel safety",
        "travel advisories",
        "best time to visit",
        "quality of life",
        "human development index",
        "happiness index",
        "social progress index",
        "gender equality",
        "gender pay gap",
        "women in parliament",
        "women in workforce",
        "child rights",
        "elderly care",
        "social welfare",
        "public services",
        "living standards",
        "famous people",
        "historical figures",
        "artists",
        "writers",
        "scientists",
        "athletes",
        "political leaders",
        "inventors",
        "companies",
        "largest companies",
        "major brands",
        "natural hazards",
        "emergency services",
        "police",
        "fire services",
        "ambulance services"
    ];

    public static List<string> ContinentFilters =
    [
        "overview",
        "general information",
        "basic facts",
        "history",
        "ancient history",
        "medieval history",
        "modern history",
        "colonial history",
        "post colonial history",
        "recent history",
        "historical timeline",
        "major historical events",
        "ancient civilizations",
        "historical empires",
        "historical kingdoms",
        "wars",
        "conflicts",
        "revolutions",
        "colonization",
        "decolonization",
        "migration history",
        "archaeological sites",
        "unesco world heritage sites",
        "geography",
        "location",
        "coordinates",
        "area",
        "land area",
        "water area",
        "coastline length",
        "regions",
        "subregions",
        "countries",
        "number of countries",
        "dependent territories",
        "largest countries",
        "smallest countries",
        "landlocked countries",
        "island countries",
        "coastal countries",
        "borders",
        "oceans and seas",
        "major seas",
        "major islands",
        "peninsulas",
        "mountains",
        "highest point",
        "lowest point",
        "mountain ranges",
        "rivers",
        "longest rivers",
        "lakes",
        "largest lakes",
        "deserts",
        "forests",
        "rainforests",
        "grasslands",
        "savannas",
        "tundra",
        "plains",
        "valleys",
        "climate",
        "climate zones",
        "average temperature",
        "average rainfall",
        "seasons",
        "weather patterns",
        "natural disasters",
        "earthquakes",
        "floods",
        "droughts",
        "hurricanes",
        "cyclones",
        "volcanoes",
        "wildfires",
        "natural resources",
        "mineral resources",
        "oil reserves",
        "gas reserves",
        "coal reserves",
        "freshwater resources",
        "land use",
        "agricultural land",
        "forest area",
        "protected areas",
        "national parks",
        "biodiversity",
        "endangered species",
        "native species",
        "invasive species",
        "environment",
        "environmental issues",
        "pollution",
        "air pollution",
        "water pollution",
        "soil pollution",
        "carbon emissions",
        "greenhouse gas emissions",
        "deforestation",
        "desertification",
        "waste management",
        "recycling rate",
        "renewable energy",
        "energy mix",
        "electricity production",
        "electricity access",
        "energy consumption",
        "population",
        "population growth",
        "population density",
        "population ranking",
        "most populated countries",
        "least populated countries",
        "largest cities",
        "major cities",
        "megacities",
        "urban areas",
        "rural areas",
        "urban population",
        "rural population",
        "urbanization rate",
        "age distribution",
        "median age",
        "children population",
        "youth population",
        "working age population",
        "elderly population",
        "dependency ratio",
        "birth rate",
        "death rate",
        "fertility rate",
        "infant mortality rate",
        "maternal mortality rate",
        "life expectancy",
        "male life expectancy",
        "female life expectancy",
        "gender ratio",
        "women vs men population",
        "male population",
        "female population",
        "migration rate",
        "net migration rate",
        "immigration",
        "emigration",
        "refugees",
        "asylum seekers",
        "diaspora",
        "ethnic groups",
        "indigenous peoples",
        "languages",
        "language families",
        "most spoken languages",
        "official languages",
        "minority languages",
        "endangered languages",
        "literacy rate",
        "male literacy rate",
        "female literacy rate",
        "religion",
        "religions",
        "major religions",
        "religious demographics",
        "religious freedom",
        "culture",
        "cultural regions",
        "traditions",
        "customs",
        "social norms",
        "festivals",
        "traditional clothing",
        "traditional music",
        "traditional dance",
        "traditional art",
        "handicrafts",
        "folklore",
        "mythology",
        "cuisine",
        "food",
        "traditional dishes",
        "street food",
        "drinks",
        "tea culture",
        "coffee culture",
        "arts",
        "literature",
        "poetry",
        "cinema",
        "theater",
        "architecture",
        "museums",
        "music",
        "dance",
        "sports",
        "popular sports",
        "olympic participation",
        "olympic medals",
        "football",
        "basketball",
        "cricket",
        "rugby",
        "athletics",
        "government",
        "political systems",
        "government types",
        "constitutions",
        "heads of state",
        "heads of government",
        "presidents",
        "prime ministers",
        "monarchies",
        "republics",
        "parliaments",
        "political parties",
        "elections",
        "voting age",
        "legal systems",
        "judiciaries",
        "law enforcement",
        "human rights",
        "civil rights",
        "freedom index",
        "press freedom",
        "internet freedom",
        "religious freedom",
        "corruption index",
        "democracy index",
        "rule of law",
        "international relations",
        "foreign policy",
        "diplomatic relations",
        "regional organizations",
        "international organizations",
        "un members",
        "military",
        "armed forces",
        "military alliances",
        "military service",
        "conscription",
        "defense spending",
        "military personnel",
        "peacekeeping missions",
        "security",
        "internal security",
        "border security",
        "terrorism risk",
        "crime rate",
        "violent crime",
        "homicide rate",
        "theft rate",
        "cybercrime",
        "prison population",
        "economy",
        "economic overview",
        "gdp",
        "nominal gdp",
        "gdp ppp",
        "gdp per capita",
        "gdp growth rate",
        "economic growth",
        "largest economies",
        "smallest economies",
        "fastest growing economies",
        "economic sectors",
        "agriculture sector",
        "industry sector",
        "services sector",
        "main industries",
        "industrial production",
        "manufacturing",
        "agriculture",
        "fishing",
        "forestry",
        "mining",
        "oil production",
        "gas production",
        "tourism sector",
        "technology sector",
        "financial sector",
        "banking sector",
        "stock markets",
        "currencies",
        "currency zones",
        "central banks",
        "inflation rate",
        "interest rates",
        "unemployment rate",
        "youth unemployment rate",
        "employment rate",
        "labor force",
        "minimum wages",
        "average salaries",
        "median income",
        "household income",
        "income inequality",
        "gini index",
        "poverty rate",
        "extreme poverty rate",
        "cost of living",
        "consumer price index",
        "public debt",
        "external debt",
        "government budgets",
        "budget deficits",
        "tax revenue",
        "tax systems",
        "corporate tax",
        "income tax",
        "vat",
        "sales tax",
        "exports",
        "imports",
        "trade balance",
        "main exports",
        "main imports",
        "trade partners",
        "export partners",
        "import partners",
        "foreign direct investment",
        "remittances",
        "economic freedom",
        "ease of doing business",
        "business environment",
        "startups",
        "innovation",
        "research and development",
        "patents",
        "education",
        "education systems",
        "primary education",
        "secondary education",
        "higher education",
        "vocational education",
        "school enrollment",
        "primary school enrollment",
        "secondary school enrollment",
        "university enrollment",
        "graduated people",
        "number of graduated people",
        "university graduates",
        "higher education rate",
        "graduation rate",
        "male graduates",
        "female graduates",
        "stem graduates",
        "literacy rate",
        "education spending",
        "public education spending",
        "private education",
        "public schools",
        "universities",
        "top universities",
        "student population",
        "teacher population",
        "student teacher ratio",
        "school life expectancy",
        "adult education",
        "research institutions",
        "healthcare",
        "healthcare systems",
        "public healthcare",
        "private healthcare",
        "healthcare spending",
        "healthcare spending per capita",
        "hospitals",
        "hospital beds",
        "doctors",
        "doctors per capita",
        "nurses",
        "nurses per capita",
        "dentists",
        "pharmacies",
        "health insurance",
        "universal healthcare",
        "vaccination rate",
        "disease burden",
        "common diseases",
        "communicable diseases",
        "noncommunicable diseases",
        "obesity rate",
        "smoking rate",
        "alcohol consumption",
        "mental health",
        "suicide rate",
        "maternal health",
        "child health",
        "nutrition",
        "undernourishment",
        "access to clean water",
        "access to sanitation",
        "infrastructure",
        "transport infrastructure",
        "road networks",
        "road length",
        "highways",
        "railways",
        "railway length",
        "metro systems",
        "public transport",
        "bus networks",
        "airports",
        "major airports",
        "national airlines",
        "ports",
        "seaports",
        "inland waterways",
        "logistics",
        "internet access",
        "internet users",
        "broadband access",
        "mobile network coverage",
        "mobile subscriptions",
        "5g coverage",
        "telephone systems",
        "postal systems",
        "housing",
        "housing markets",
        "home ownership",
        "rent prices",
        "utilities",
        "water supply",
        "sanitation",
        "electricity grids",
        "science",
        "technology",
        "digital economy",
        "e government",
        "cybersecurity",
        "space programs",
        "artificial intelligence",
        "biotechnology",
        "media",
        "television",
        "radio",
        "newspapers",
        "social media usage",
        "tourism",
        "tourist attractions",
        "tourism revenue",
        "annual visitors",
        "most visited countries",
        "most visited cities",
        "landmarks",
        "beaches",
        "historic sites",
        "religious sites",
        "natural attractions",
        "travel safety",
        "travel advisories",
        "best time to visit",
        "quality of life",
        "human development index",
        "happiness index",
        "social progress index",
        "gender equality",
        "gender pay gap",
        "women in parliament",
        "women in workforce",
        "child rights",
        "elderly care",
        "social welfare",
        "public services",
        "living standards",
        "famous people",
        "historical figures",
        "artists",
        "writers",
        "scientists",
        "athletes",
        "political leaders",
        "inventors",
        "companies",
        "largest companies",
        "major brands",
        "emergency services",
        "police",
        "fire services",
        "ambulance services"
    ];
}